### ISSUE TITLE
Error in laravel 8

### ISSUE THREAD

**Issue by hrace009** [brian2694/laravel-toastr#11]
I got this error,

![image](https://user-images.githubusercontent.com/7691118/154729012-55e8a63c-b4a0-43b7-b8aa-30712d32c83a.png)

Any advice?

**Comment by brian2694** [comment]
What version of php are you using? I will test locally

**Comment by hrace009** [comment]
> What version of php are you using? I will test locally

```
[hrace009@localhost]$ php -v
PHP 7.4.27 (cli) (built: Dec 14 2021 17:17:06) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with the ionCube PHP Loader + ionCube24 v11.0.0, Copyright (c) 2002-2021, by ionCube Ltd.
```

**Comment by brian2694** [comment]
Let me check your code. 

I've tested locally on php 7.4 and Laravel 8 and see everything working fine.

This way I am calling Toastr
`Toastr::success('Messages in here', 'Title', ["positionClass" => "toast-top-center"]);`

I leave you a screenshot below

![image](https://user-images.githubusercontent.com/5945156/154888164-745b20bd-e77a-4160-a42f-2904bb153a20.png)

**Comment by brian2694** [comment]
Any update?

**Comment by hrace009** [comment]
hi, sorry late to respond, i have move to sweetalert2.

Thanks
