### ISSUE TITLE
Provide PHP DOC to the Toastr Facade

### ISSUE THREAD

**Issue by antonio8101** [brian2694/laravel-toastr#14]
To help IDEs suggets Toastr Facade methods, and usages of those methods, some PHP DOC should be provided on the Toastr Facade class

**Comment by antonio8101** [comment]
It can be solved with PR #15

**Comment by brian2694** [comment]
Thank you so much.

**Comment by brian2694** [comment]
Thank you for your collaboration. Version 5.58 has already been released with these changes. I've also added your name and your link to the readme as a contributor to this repository.
