### ISSUE TITLE
Toastr show in every routes

### ISSUE THREAD

**Issue by DevTiago** [brian2694/laravel-toastr#9]
Greetings all, 

First of all, thanks for the package!

I'm using it on a Laravel 8 project and i have a little issue. First, i've set this on my layout:
```
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" integrity="sha512-vKMx8UnXk60zUwyUnUPM3HbQo8QfmNx7+ltw8Pm5zLusl1XIfwcxo8DbWCqMGKaWeNxWA8yrx5v3SaVpMvR3CA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>
      ...
      <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

     {!! Toastr::message() !!}
</body>
</html>
```

Then, on my controller i have a method where i fire a Toastr and return a view:

```
 public function dashboard() {

   Toastr::success('Messages in here', 'Title', ["positionClass" => "toast-top-center"]);

   return view('admin.dashboard');

}
```

and that works fine but when i go to another route where i don't have any Toastr, the same Toastr get's fired...

Am i missing something here?

Thanks for the help!

**Comment by brian2694** [comment]
Are you using octane to speed up your application? Or something similar that leaves the application live? If so, try flushing with Toastr :: clear ()

**Comment by Noman73** [comment]
same problem! when i reload the same view then the message show again and again how can i solved it. please suggest me
@brian2694

**Comment by brian2694** [comment]
@Noman73 Are you using octane to speed up your application? Or something similar that leaves the application live? If so, try flushing with Toastr::clear()
